version : '3.8'


services:
  nginx:
    container_name: nginx-prod
    image: nginx:latest
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/blue_green:/proxy
    environment:
      - TZ=Asia/Seoul
    networks:
      - chaekbang-prod-net
      - chaekbang-webserver-net

networks:
  chaekbang-prod-net:
    external: true
    name: "chaekbang-prod-net"
  chaekbang-webserver-net:
    external: true
    name: "chaekbang-webserver-net"