version: "3.8"

services:
  dev-spring-app:
    container_name: dev-spring-app
    image: joslynn/dev-spring-app:latest
    environment:
      PROFILE: dev
      MYSQL_HOST: dev-mysql
    expose:
      - "8080"
    networks:
      - chaekbang-dev-net
networks:
  chaekbang-dev-net:
    external: true
    name: "chaekbang-dev-net"
