spring:
  datasource:
    url: jdbc:mysql://dev-mysql:3306/chaekbang_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: junit6_dev-mysql_passwd_by_jojo!
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
  redis:
    host: dev-redis
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
    password: junit6_dev-redis_passwd_by_jojo!

server:
  port: 8081

