spring:
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 20
  config:
    import: application.properties
    
logging:
  level:
    com.jsix.chaekbang: DEBUG
---
spring:
  config:
    activate:
      on-profile: test
    import: application.properties
  datasource:
    url: jdbc:h2:mem:~/chackbangdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
