insert into user(user_id, oauth_id, oauth_provider, email, nickname, gender, birth_date, about_me,
                 profile_image_url, created_at, modified_at)
values (null, 'jojo', 'KAKAO', 'jojo@email.com', 'jojo', 'F', '1999-01-01', ' jojo 안녕하세요',
        'https://chaekbang-bucket.s3.ap-northeast-2.amazonaws.com/user/image/DEFAULT_USER_PROFILE.png',
        now(), null),
       (null, 'jin', 'KAKAO', 'jin@email.com', 'jin', 'F', '1999-01-01', ' jin 안녕하세요',
        'https://chaekbang-bucket.s3.ap-northeast-2.amazonaws.com/user/image/DEFAULT_USER_PROFILE.png',
        now(),
        null),
       (null, 'jun', 'KAKAO', 'jun@email.com', 'jun', 'F', '1999-01-01', ' jun 안녕하세요',
        'https://chaekbang-bucket.s3.ap-northeast-2.amazonaws.com/user/image/DEFAULT_USER_PROFILE.png',
        now(),
        null),
       (null, 'joby', 'KAKAO', 'joby@email.com', 'joby', 'F', '1999-01-01', 'joby 안녕하세요',
        'https://chaekbang-bucket.s3.ap-northeast-2.amazonaws.com/user/image/DEFAULT_USER_PROFILE.png',
        now(), null),
       (null, 'james', 'KAKAO', 'james@email.com', 'james', 'F', '1999-01-01', 'james 안녕하세요',
        'https://chaekbang-bucket.s3.ap-northeast-2.amazonaws.com/user/image/DEFAULT_USER_PROFILE.png',
        now(), null),
       (null, 'jinx', 'KAKAO', 'jinx@email.com', 'jinx', 'F', '1999-01-01', 'jinx 안녕하세요',
        'https://chaekbang-bucket.s3.ap-northeast-2.amazonaws.com/user/image/DEFAULT_USER_PROFILE.png',
        now(), null);
