version: '3.8'

services:
  nginx:
    container_name: nginx-main
    image: nginx:latest
    restart: always
      #외부와 소통하는 경우에는 ports로 포트 설정.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/certbot/conf:/etc/letsencrypt:ro"
      - "./data/certbot/www:/var/www/certbot:ro"
      - "/var/lib/docker/volumes/jenkins_jenkins-data/_data/workspace/chaekbang_front/Frontend/build:/var/chaekbang_front"
    environment:
      - TZ=Asia/Seoul
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - chaekbang-webserver-net
      - chaekbang-jenkins-net

  certbot:
    container_name: webserver-certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt:rw"
      - "./data/certbot/www:/var/www/certbot:rw"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  chaekbang-webserver-net:
    external: true
    name: "chaekbang-webserver-net"
  chaekbang-jenkins-net:
    external: true
    name: "chaekbang-jenkins-net"